INSERT INTO books (author, title, publishing_year, category, available) VALUES ('Roland Tõnisson', 'Serafim ja Silvia', 2024, 'Ilukirjandus', FALSE);
INSERT INTO books (author, title, publishing_year, category, available) VALUES ('Andrus Kivirähk', 'Jumala lood', 2009, 'Ilukirjandus', FALSE);
INSERT INTO books (author, title, publishing_year, category, available) VALUES ('Toomas Sulling', 'Südamega Südamest', 2017, 'Tervis', FALSE);
INSERT INTO books (author, title, publishing_year, category, available) VALUES ('Kari Hotakainen', 'Kimi Räikkönen', 2018, 'Biograafia', TRUE);
INSERT INTO books (author, title, publishing_year, category, available) VALUES ('Marika Vingissar', 'Head eesti toidud', 2024, 'Kokandus', TRUE);
INSERT INTO books (author, title, publishing_year, category, available) VALUES ('Indrek Schwede', 'Mart Poom: minu lugu', 2014, 'Biograafia', TRUE);
INSERT INTO books (author, title, publishing_year, category, available) VALUES ('Jamie Oliver', 'Jamie Oliver. Koos', 2021, 'Kokandus', FALSE);
INSERT INTO books (author, title, publishing_year, category, available) VALUES ('David Lagercrantz', 'I am Zlatan Ibrahimovic', 2011, 'Biograafia', TRUE);
INSERT INTO books (author, title, publishing_year, category, available) VALUES ('Silvi Väljal', 'Jussikese seitse sõpra', 1999, 'Lastekirjandus', FALSE);
INSERT INTO books (author, title, publishing_year, category, available) VALUES ('Andrus Kivirähk', 'Lotte reis lõunamaale', 2021, 'Lastekirjandus', TRUE);
